### ISSUE TITLE
I'm not getting the Image the way you did

### ISSUE THREAD

**Issue by lifeeric** [lawwantsin/webpack-course#3]
before everythin' was workin' correctIy, but now it getting this problem below. I'm pretty sure I made a mistake with webpack5.

Log: 
```
ERROR in ./src/index.html
Module build failed (from ./node_modules/extract-loader/lib/extractLoader.js):
/home/vlife/Projects/webpack-5/src/images/link.jpg:1
export default __webpack_public_path__ + "images/link.jpg";
^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:79:7)
    at /home/vlife/Projects/webpack-5/node_modules/extract-loader/lib/extractLoader.js:81:28
    at Generator.next (<anonymous>)
    at step (/home/vlife/Projects/webpack-5/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/vlife/Projects/webpack-5/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/home/vlife/Projects/webpack-5/node_modules/core-js/library/modules/_export.js:36:28)
    at /home/vlife/Projects/webpack-5/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at evalModule (/home/vlife/Projects/webpack-5/node_modules/extract-loader/lib/extractLoader.js:150:63)
    at /home/vlife/Projects/webpack-5/node_modules/extract-loader/lib/extractLoader.js:138:28
 @ ./src/main.js 1:0-23

ℹ ｢wdm｣: Failed to compile.

```

**Okay I found it**, we also need to upload image to main.js which as entry package, thanks!

**_Please delete this issue!_**

**Comment by clshu** [comment]
I encountered the same message but for different reason. In the lecture, the <img> tag is shown as 
\<img src="./images/link.jpg" alt=""\>. I kept having the same error message until I changed it to "/images/link.jpg" without a dot. I double checked with loaders2-final branch and it doesn't have a dot. So was it corrected but not shown in the video? It kept me stuck for a while and very frustrating. See 6:35 in Section 2, #5. It said it required a relative path. My packages are as followed 

"dependencies": {
    "css-loader": "^3.4.0",
    "extract-loader": "^3.1.0",
    "file-loader": "^5.0.2",
    "html-loader": "^0.5.5",
    "style-loader": "^1.1.2",
    "webpack": "^4.41.5",
    "webpack-cli": "^3.3.10",
    "webpack-dev-server": "^3.10.1"
  }
